#******************************************************************************
# CONFIGURE
# - BOOT VERSION		: 050: S132 v201, 055: S132 v500
#******************************************************************************
VERSION_MAJOR    = 5
VERSION_MINOR    = 0
VERSION_REVISION = 2

include ../make_common.mk

C_SOURCE_FILES += $(SDK_PATH)/libraries/bootloader_dfu/dfu_dual_bank.c
